{{- if eq .Values.vectorizer.active "ollama" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "goat-yard-archive.fullname" . }}-ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ollama
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ollama
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: ollama
          image: "{{ .Values.vectorizer.ollama.image }}:{{ .Values.vectorizer.ollama.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 11434
              protocol: TCP
          resources:
            {{- toYaml .Values.vectorizer.ollama.resources | nindent 12 }}
          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama
          lifecycle:
            postStart:
              exec:
                command: 
                  - /bin/sh
                  - -c
                  - "sleep 5 && ollama pull {{ .Values.vectorizer.ollama.model }}"
      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: {{ include "goat-yard-archive.fullname" . }}-ollama-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: 11434
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "goat-yard-archive.fullname" . }}-ollama-pvc
  labels:
    app.kubernetes.io/name: ollama
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
{{- end }}
