import React from 'react';

interface TermsProps {
    onClose: () => void;
}

const Terms: React.FC<TermsProps> = ({ onClose }) => {
    return (
        <div className="relative bg-[#FFFDF5] min-h-full">
            {/* Sticky Header */}
            <div className="sticky top-0 z-10 bg-[#EFEBE9] px-6 py-4 border-b border-[#D7CCC8] flex justify-between items-center shadow-sm">
                <h1 className="text-[#3E2723] font-serif font-bold text-xl uppercase tracking-wide">Terms of Use</h1>
                <button
                    onClick={onClose}
                    className="text-[#8D6E63] hover:text-[#3E2723] flex items-center gap-2 font-bold px-3 py-1 rounded hover:bg-[#D7CCC8]/30 transition-colors"
                    title="Close"
                >
                    <span className="text-lg">✕</span>
                    <span className="text-sm uppercase tracking-wider">Close</span>
                </button>
            </div>

            <div className="max-w-4xl mx-auto px-6 py-12">

                {/* Date Header */}
                <div className="border-b border-[#D7CCC8] pb-6 mb-8">
                    <p className="text-[#8D6E63] font-serif italic">Last updated: December 31, 2025</p>
                </div>

                {/* Main Content */}
                <div className="prose prose-stone max-w-none text-[#5D4037] space-y-8 font-serif leading-relaxed">

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">AGREEMENT TO OUR LEGAL TERMS</h2>
                        <p>
                            We are <strong>Edgy Solutions</strong> ("Company," "we," "us," "our"). We operate the Dr. Voluminous application,
                            as well as any other related products and services that refer or link to these legal terms (the "Legal Terms") (collectively, the "Services").
                        </p>
                        <p>
                            You can contact us by email at <strong>privacy@goatyardarchive.org</strong>.
                        </p>
                        <p>
                            These Legal Terms constitute a legally binding agreement made between you, whether personally or on behalf of an entity ("you"), and Edgy Solutions,
                            concerning your access to and use of the Services. You agree that by accessing the Services, you have read, understood, and agreed to be bound by
                            all of these Legal Terms. IF YOU DO NOT AGREE WITH ALL OF THESE LEGAL TERMS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SERVICES AND YOU MUST DISCONTINUE USE IMMEDIATELY.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">1. OUR SERVICES</h2>
                        <p>
                            The information provided when using the Services is not intended for distribution to or use by any person or entity in any jurisdiction or country where such
                            distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the Services from other locations do so on their
                            own initiative and are solely responsible for compliance with local laws.
                        </p>
                    </section>

                    {/* --- CUSTOM CLAUSE: RESEARCH & AI LIMITATIONS --- */}
                    <div className="bg-[#EFEBE9] border-l-4 border-[#8D6E63] p-6 my-6 rounded-r shadow-inner">
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">2. RESEARCH ALPHA & AI LIMITATIONS</h2>
                        <ul className="list-decimal pl-5 space-y-3 marker:text-[#8D6E63]">
                            <li>
                                <strong>Alpha Status:</strong> You acknowledge that "Dr. Voluminous" is in a pre-alpha research state. The Service may contain bugs, errors, and may experience significant downtime. We reserve the right to wipe data or reset accounts at any time without notice.
                            </li>
                            <li>
                                <strong>AI Hallucinations:</strong> The theological content, citations, and summaries are generated by Artificial Intelligence.
                                <span className="font-bold text-[#3E2723]"> The Service may generate incorrect, misleading, or historically inaccurate information ("Hallucinations"). </span>
                                You agree that you are solely responsible for verifying all citations against the provided original text images.
                            </li>
                            <li>
                                <strong>No Theological Authority:</strong> This tool is for research assistance only and does not constitute pastoral advice, doctrinal authority, or absolute truth. Edgy Solutions is not liable for any theological errors or misunderstandings resulting from the use of this Service.
                            </li>
                            <li>
                                <strong>Feedback Ownership:</strong> Any feedback, error reports, or theological corrections you provide to us shall be the intellectual property of Edgy Solutions, which we may use to train our models without compensation to you.
                            </li>
                        </ul>
                    </div>
                    {/* ------------------------------------------------ */}

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">3. INTELLECTUAL PROPERTY RIGHTS</h2>
                        <p>
                            We are the owner or the licensee of all intellectual property rights in our Services, including all source code, databases, functionality, software, website designs,
                            audio, video, text, photographs, and graphics in the Services (collectively, the "Content"), as well as the trademarks, service marks, and logos contained therein.
                        </p>
                        <p>
                            Our Content and Marks are protected by copyright and trademark laws. The Content is provided "AS IS" for your personal, non-commercial use or internal business purpose only.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">4. USER REPRESENTATIONS</h2>
                        <p>By using the Services, you represent and warrant that:</p>
                        <ol className="list-decimal pl-5 space-y-1 marker:text-[#8D6E63]">
                            <li>You have the legal capacity and you agree to comply with these Legal Terms;</li>
                            <li>You are not a minor in the jurisdiction in which you reside;</li>
                            <li>You will not access the Services through automated or non-human means, whether through a bot, script or otherwise;</li>
                            <li>You will not use the Services for any illegal or unauthorized purpose;</li>
                            <li>Your use of the Services will not violate any applicable law or regulation.</li>
                        </ol>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">5. PROHIBITED ACTIVITIES</h2>
                        <p>You may not access or use the Services for any purpose other than that for which we make the Services available. As a user of the Services, you agree not to:</p>
                        <ul className="list-disc pl-5 space-y-1 marker:text-[#8D6E63]">
                            <li>Systematically retrieve data or other content from the Services to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
                            <li>Trick, defraud, or mislead us and other users, especially in any attempt to learn sensitive account information such as user passwords.</li>
                            <li>Circumvent, disable, or otherwise interfere with security-related features of the Services.</li>
                            <li>Disparage, tarnish, or otherwise harm, in our opinion, us and/or the Services.</li>
                            <li>Use the Services in a manner inconsistent with any applicable laws or regulations.</li>
                            <li>Upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material.</li>
                        </ul>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">6. USER GENERATED CONTRIBUTIONS</h2>
                        <p>
                            The Services does not offer users to submit or post content publicly. However, we may provide you with the opportunity to create, submit, or transmit content and materials to us
                            (e.g., feedback, chat queries). By submitting suggestions or other feedback regarding the Services, you agree that we can use and share such feedback for any purpose without compensation to you.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">7. LIMITATIONS OF LIABILITY</h2>
                        <p className="uppercase">
                            IN NO EVENT WILL WE OR OUR DIRECTORS, EMPLOYEES, OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DIRECT, INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL,
                            OR PUNITIVE DAMAGES, INCLUDING LOST PROFIT, LOST REVENUE, LOSS OF DATA, OR OTHER DAMAGES ARISING FROM YOUR USE OF THE SERVICES, EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">8. TERM AND TERMINATION</h2>
                        <p>
                            These Legal Terms shall remain in full force and effect while you use the Services. WITHOUT LIMITING ANY OTHER PROVISION OF THESE LEGAL TERMS, WE RESERVE THE RIGHT TO,
                            IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES, TO ANY PERSON FOR ANY REASON.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">9. GOVERNING LAW</h2>
                        <p>
                            These Legal Terms shall be governed by and defined following the laws of the State of Alabama, United States. Edgy Solutions and yourself irrevocably consent that
                            the courts of Alabama shall have exclusive jurisdiction to resolve any dispute which may arise in connection with these Legal Terms.
                        </p>
                    </section>

                    <section className="border-t border-[#D7CCC8] pt-8 mt-8">
                        <h2 className="text-xl font-bold text-[#3E2723] mb-3 uppercase tracking-wider">10. CONTACT US</h2>
                        <p className="mb-4">In order to resolve a complaint regarding the Services or to receive further information regarding use of the Services, please contact us at:</p>
                        <div className="bg-[#EFEBE9] p-6 rounded text-[#5D4037] border border-[#D7CCC8]">
                            <p className="font-bold text-[#3E2723]">Edgy Solutions</p>
                            <p>Rogersville, AL 35652</p>
                            <p>United States</p>
                            <p className="mt-4"><strong>Email:</strong> privacy@goatyardarchive.org</p>
                        </div>
                    </section>

                </div>
            </div>
        </div>
    );
};

export default Terms;
