# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractGillKnowledge(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGillKnowledge", llm_response=llm_response, mode="request")
        return typing.cast(types.ExtractionResult, result)

    def ExtractTextFromImage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTextFromImage", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def ExtractVersesFromMarkdown(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.VerseChunk"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVersesFromMarkdown", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.VerseChunk"], result)

    def NormalizeGillMarkdown(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="NormalizeGillMarkdown", llm_response=llm_response, mode="request")
        return typing.cast(str, result)

    def ValidateMetadataCore(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MetadataCore:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMetadataCore", llm_response=llm_response, mode="request")
        return typing.cast(types.MetadataCore, result)

    def ValidateMetadataVerses(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.MetadataVerses:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMetadataVerses", llm_response=llm_response, mode="request")
        return typing.cast(types.MetadataVerses, result)

    def ValidateOCRMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.Metadata:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateOCRMetadata", llm_response=llm_response, mode="request")
        return typing.cast(types.Metadata, result)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ExtractGillKnowledge(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ExtractionResult:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractGillKnowledge", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ExtractionResult, result)

    def ExtractTextFromImage(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractTextFromImage", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def ExtractVersesFromMarkdown(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.VerseChunk"]:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ExtractVersesFromMarkdown", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.VerseChunk"], result)

    def NormalizeGillMarkdown(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> str:
        result = self.__options.merge_options(baml_options).parse_response(function_name="NormalizeGillMarkdown", llm_response=llm_response, mode="stream")
        return typing.cast(str, result)

    def ValidateMetadataCore(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MetadataCore:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMetadataCore", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MetadataCore, result)

    def ValidateMetadataVerses(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.MetadataVerses:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateMetadataVerses", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.MetadataVerses, result)

    def ValidateOCRMetadata(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.Metadata:
        result = self.__options.merge_options(baml_options).parse_response(function_name="ValidateOCRMetadata", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.Metadata, result)

    