# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class ExtractedText(BaseModel):
    text: typing.Optional[str] = None

class ExtractionResult(BaseModel):
    entities: typing.List["GillEntity"]
    cross_references: typing.List[str]

class GillEntity(BaseModel):
    name: typing.Optional[str] = None
    category: typing.Optional[types.EntityCategory] = None
    biblical_era: typing.Optional[types.BiblicalEra] = None
    role: typing.Optional[str] = None
    normalized_name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class Metadata(BaseModel):
    book_name: typing.Optional[str] = None
    chapter: typing.Optional[int] = None
    verse: typing.Optional[str] = None
    page_number: typing.Optional[int] = None

class VerseChunk(BaseModel):
    verse_ref: typing.Optional[str] = None
    start_phrase: typing.Optional[str] = None
    end_phrase: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
