# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__

class BamlSyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def __getstate__(self):
        # Return state needed for pickling
        return {"options": self.__options}

    def __setstate__(self, state):
        # Restore state from pickling
        self.__options = state["options"]
        self.__stream_client = BamlStreamClient(self.__options)
        self.__http_request = BamlHttpRequestClient(self.__options)
        self.__http_stream_request = BamlHttpStreamRequestClient(self.__options)
        self.__llm_response_parser = LlmResponseParser(self.__options)
        self.__llm_stream_parser = LlmStreamParser(self.__options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlSyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlSyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser
    
    def AnalyzeRAGFailure(self, question: str,context: str,manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> types.RAGAnalysis:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.AnalyzeRAGFailure(question=question,context=context,manifest=manifest,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="AnalyzeRAGFailure", args={
                "question": question,"context": context,"manifest": manifest,
            })
            return typing.cast(types.RAGAnalysis, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractGillKnowledge(self, commentary_text: str,previous_entities: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.ExtractionResult:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractGillKnowledge(commentary_text=commentary_text,previous_entities=previous_entities,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractGillKnowledge", args={
                "commentary_text": commentary_text,"previous_entities": previous_entities,
            })
            return typing.cast(types.ExtractionResult, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractTextFromImage(self, image: baml_py.Image,book: typing.Optional[str] = None,chapter: typing.Optional[str] = None,verse: typing.Optional[str] = None,page_number: typing.Optional[str] = None,hebrew_text: typing.Optional[str] = None,greek_text: typing.Optional[str] = None,ocr_text: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractTextFromImage(image=image,book=book,chapter=chapter,verse=verse,page_number=page_number,hebrew_text=hebrew_text,greek_text=greek_text,ocr_text=ocr_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractTextFromImage", args={
                "image": image,"book": book,"chapter": chapter,"verse": verse,"page_number": page_number,"hebrew_text": hebrew_text,"greek_text": greek_text,"ocr_text": ocr_text,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def ExtractVersesFromMarkdown(self, markdown_text: str,
        baml_options: BamlCallOptions = {},
    ) -> typing.List["types.VerseChunk"]:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ExtractVersesFromMarkdown(markdown_text=markdown_text,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ExtractVersesFromMarkdown", args={
                "markdown_text": markdown_text,
            })
            return typing.cast(typing.List["types.VerseChunk"], result.cast_to(types, types, stream_types, False, __runtime__))
    def NormalizeGillMarkdown(self, raw_markdown: str,
        baml_options: BamlCallOptions = {},
    ) -> str:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.NormalizeGillMarkdown(raw_markdown=raw_markdown,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="NormalizeGillMarkdown", args={
                "raw_markdown": raw_markdown,
            })
            return typing.cast(str, result.cast_to(types, types, stream_types, False, __runtime__))
    def OptimizeSearchQuery(self, user_query: str,available_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.OptimizedQuery:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.OptimizeSearchQuery(user_query=user_query,available_entities=available_entities,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="OptimizeSearchQuery", args={
                "user_query": user_query,"available_entities": available_entities,
            })
            return typing.cast(types.OptimizedQuery, result.cast_to(types, types, stream_types, False, __runtime__))
    def ResolveBoundaryPronouns(self, unresolved_text: str,previous_text: str,previous_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> types.ResolvedPronoun:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ResolveBoundaryPronouns(unresolved_text=unresolved_text,previous_text=previous_text,previous_entities=previous_entities,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ResolveBoundaryPronouns", args={
                "unresolved_text": unresolved_text,"previous_text": previous_text,"previous_entities": previous_entities,
            })
            return typing.cast(types.ResolvedPronoun, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateMetadataCore(self, image: baml_py.Image,ocr_metadata: types.MetadataCore,
        baml_options: BamlCallOptions = {},
    ) -> types.MetadataCore:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateMetadataCore(image=image,ocr_metadata=ocr_metadata,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateMetadataCore", args={
                "image": image,"ocr_metadata": ocr_metadata,
            })
            return typing.cast(types.MetadataCore, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateMetadataVerses(self, image: baml_py.Image,chapter: typing.Optional[int] = None,verse_hint: typing.Optional[str] = None,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.MetadataVerses:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateMetadataVerses(image=image,chapter=chapter,verse_hint=verse_hint,body_verses=body_verses,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateMetadataVerses", args={
                "image": image,"chapter": chapter,"verse_hint": verse_hint,"body_verses": body_verses,
            })
            return typing.cast(types.MetadataVerses, result.cast_to(types, types, stream_types, False, __runtime__))
    def ValidateOCRMetadata(self, image: baml_py.Image,ocr_metadata: types.Metadata,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> types.Metadata:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            stream = self.stream.ValidateOCRMetadata(image=image,ocr_metadata=ocr_metadata,body_verses=body_verses,
                baml_options=baml_options)
            return stream.get_final_response()
        else:
            # Original non-streaming code
            result = self.__options.merge_options(baml_options).call_function_sync(function_name="ValidateOCRMetadata", args={
                "image": image,"ocr_metadata": ocr_metadata,"body_verses": body_verses,
            })
            return typing.cast(types.Metadata, result.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeRAGFailure(self, question: str,context: str,manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.RAGAnalysis, types.RAGAnalysis]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="AnalyzeRAGFailure", args={
            "question": question,"context": context,"manifest": manifest,
        })
        return baml_py.BamlSyncStream[stream_types.RAGAnalysis, types.RAGAnalysis](
          result,
          lambda x: typing.cast(stream_types.RAGAnalysis, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.RAGAnalysis, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractGillKnowledge(self, commentary_text: str,previous_entities: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ExtractionResult, types.ExtractionResult]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractGillKnowledge", args={
            "commentary_text": commentary_text,"previous_entities": previous_entities,
        })
        return baml_py.BamlSyncStream[stream_types.ExtractionResult, types.ExtractionResult](
          result,
          lambda x: typing.cast(stream_types.ExtractionResult, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ExtractionResult, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractTextFromImage(self, image: baml_py.Image,book: typing.Optional[str] = None,chapter: typing.Optional[str] = None,verse: typing.Optional[str] = None,page_number: typing.Optional[str] = None,hebrew_text: typing.Optional[str] = None,greek_text: typing.Optional[str] = None,ocr_text: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractTextFromImage", args={
            "image": image,"book": book,"chapter": chapter,"verse": verse,"page_number": page_number,"hebrew_text": hebrew_text,"greek_text": greek_text,"ocr_text": ocr_text,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ExtractVersesFromMarkdown(self, markdown_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[typing.List["stream_types.VerseChunk"], typing.List["types.VerseChunk"]]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ExtractVersesFromMarkdown", args={
            "markdown_text": markdown_text,
        })
        return baml_py.BamlSyncStream[typing.List["stream_types.VerseChunk"], typing.List["types.VerseChunk"]](
          result,
          lambda x: typing.cast(typing.List["stream_types.VerseChunk"], x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(typing.List["types.VerseChunk"], x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def NormalizeGillMarkdown(self, raw_markdown: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[str, str]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="NormalizeGillMarkdown", args={
            "raw_markdown": raw_markdown,
        })
        return baml_py.BamlSyncStream[str, str](
          result,
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(str, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def OptimizeSearchQuery(self, user_query: str,available_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.OptimizedQuery, types.OptimizedQuery]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="OptimizeSearchQuery", args={
            "user_query": user_query,"available_entities": available_entities,
        })
        return baml_py.BamlSyncStream[stream_types.OptimizedQuery, types.OptimizedQuery](
          result,
          lambda x: typing.cast(stream_types.OptimizedQuery, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.OptimizedQuery, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ResolveBoundaryPronouns(self, unresolved_text: str,previous_text: str,previous_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.ResolvedPronoun, types.ResolvedPronoun]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ResolveBoundaryPronouns", args={
            "unresolved_text": unresolved_text,"previous_text": previous_text,"previous_entities": previous_entities,
        })
        return baml_py.BamlSyncStream[stream_types.ResolvedPronoun, types.ResolvedPronoun](
          result,
          lambda x: typing.cast(stream_types.ResolvedPronoun, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.ResolvedPronoun, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateMetadataCore(self, image: baml_py.Image,ocr_metadata: types.MetadataCore,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MetadataCore, types.MetadataCore]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateMetadataCore", args={
            "image": image,"ocr_metadata": ocr_metadata,
        })
        return baml_py.BamlSyncStream[stream_types.MetadataCore, types.MetadataCore](
          result,
          lambda x: typing.cast(stream_types.MetadataCore, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MetadataCore, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateMetadataVerses(self, image: baml_py.Image,chapter: typing.Optional[int] = None,verse_hint: typing.Optional[str] = None,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.MetadataVerses, types.MetadataVerses]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateMetadataVerses", args={
            "image": image,"chapter": chapter,"verse_hint": verse_hint,"body_verses": body_verses,
        })
        return baml_py.BamlSyncStream[stream_types.MetadataVerses, types.MetadataVerses](
          result,
          lambda x: typing.cast(stream_types.MetadataVerses, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.MetadataVerses, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    def ValidateOCRMetadata(self, image: baml_py.Image,ocr_metadata: types.Metadata,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlSyncStream[stream_types.Metadata, types.Metadata]:
        ctx, result = self.__options.merge_options(baml_options).create_sync_stream(function_name="ValidateOCRMetadata", args={
            "image": image,"ocr_metadata": ocr_metadata,"body_verses": body_verses,
        })
        return baml_py.BamlSyncStream[stream_types.Metadata, types.Metadata](
          result,
          lambda x: typing.cast(stream_types.Metadata, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.Metadata, x.cast_to(types, types, stream_types, False, __runtime__)),
          ctx,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeRAGFailure(self, question: str,context: str,manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeRAGFailure", args={
            "question": question,"context": context,"manifest": manifest,
        }, mode="request")
        return result
    def ExtractGillKnowledge(self, commentary_text: str,previous_entities: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGillKnowledge", args={
            "commentary_text": commentary_text,"previous_entities": previous_entities,
        }, mode="request")
        return result
    def ExtractTextFromImage(self, image: baml_py.Image,book: typing.Optional[str] = None,chapter: typing.Optional[str] = None,verse: typing.Optional[str] = None,page_number: typing.Optional[str] = None,hebrew_text: typing.Optional[str] = None,greek_text: typing.Optional[str] = None,ocr_text: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextFromImage", args={
            "image": image,"book": book,"chapter": chapter,"verse": verse,"page_number": page_number,"hebrew_text": hebrew_text,"greek_text": greek_text,"ocr_text": ocr_text,
        }, mode="request")
        return result
    def ExtractVersesFromMarkdown(self, markdown_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVersesFromMarkdown", args={
            "markdown_text": markdown_text,
        }, mode="request")
        return result
    def NormalizeGillMarkdown(self, raw_markdown: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="NormalizeGillMarkdown", args={
            "raw_markdown": raw_markdown,
        }, mode="request")
        return result
    def OptimizeSearchQuery(self, user_query: str,available_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="OptimizeSearchQuery", args={
            "user_query": user_query,"available_entities": available_entities,
        }, mode="request")
        return result
    def ResolveBoundaryPronouns(self, unresolved_text: str,previous_text: str,previous_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResolveBoundaryPronouns", args={
            "unresolved_text": unresolved_text,"previous_text": previous_text,"previous_entities": previous_entities,
        }, mode="request")
        return result
    def ValidateMetadataCore(self, image: baml_py.Image,ocr_metadata: types.MetadataCore,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMetadataCore", args={
            "image": image,"ocr_metadata": ocr_metadata,
        }, mode="request")
        return result
    def ValidateMetadataVerses(self, image: baml_py.Image,chapter: typing.Optional[int] = None,verse_hint: typing.Optional[str] = None,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMetadataVerses", args={
            "image": image,"chapter": chapter,"verse_hint": verse_hint,"body_verses": body_verses,
        }, mode="request")
        return result
    def ValidateOCRMetadata(self, image: baml_py.Image,ocr_metadata: types.Metadata,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateOCRMetadata", args={
            "image": image,"ocr_metadata": ocr_metadata,"body_verses": body_verses,
        }, mode="request")
        return result
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeRAGFailure(self, question: str,context: str,manifest: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="AnalyzeRAGFailure", args={
            "question": question,"context": context,"manifest": manifest,
        }, mode="stream")
        return result
    def ExtractGillKnowledge(self, commentary_text: str,previous_entities: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractGillKnowledge", args={
            "commentary_text": commentary_text,"previous_entities": previous_entities,
        }, mode="stream")
        return result
    def ExtractTextFromImage(self, image: baml_py.Image,book: typing.Optional[str] = None,chapter: typing.Optional[str] = None,verse: typing.Optional[str] = None,page_number: typing.Optional[str] = None,hebrew_text: typing.Optional[str] = None,greek_text: typing.Optional[str] = None,ocr_text: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractTextFromImage", args={
            "image": image,"book": book,"chapter": chapter,"verse": verse,"page_number": page_number,"hebrew_text": hebrew_text,"greek_text": greek_text,"ocr_text": ocr_text,
        }, mode="stream")
        return result
    def ExtractVersesFromMarkdown(self, markdown_text: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ExtractVersesFromMarkdown", args={
            "markdown_text": markdown_text,
        }, mode="stream")
        return result
    def NormalizeGillMarkdown(self, raw_markdown: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="NormalizeGillMarkdown", args={
            "raw_markdown": raw_markdown,
        }, mode="stream")
        return result
    def OptimizeSearchQuery(self, user_query: str,available_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="OptimizeSearchQuery", args={
            "user_query": user_query,"available_entities": available_entities,
        }, mode="stream")
        return result
    def ResolveBoundaryPronouns(self, unresolved_text: str,previous_text: str,previous_entities: typing.List[str],
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ResolveBoundaryPronouns", args={
            "unresolved_text": unresolved_text,"previous_text": previous_text,"previous_entities": previous_entities,
        }, mode="stream")
        return result
    def ValidateMetadataCore(self, image: baml_py.Image,ocr_metadata: types.MetadataCore,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMetadataCore", args={
            "image": image,"ocr_metadata": ocr_metadata,
        }, mode="stream")
        return result
    def ValidateMetadataVerses(self, image: baml_py.Image,chapter: typing.Optional[int] = None,verse_hint: typing.Optional[str] = None,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateMetadataVerses", args={
            "image": image,"chapter": chapter,"verse_hint": verse_hint,"body_verses": body_verses,
        }, mode="stream")
        return result
    def ValidateOCRMetadata(self, image: baml_py.Image,ocr_metadata: types.Metadata,body_verses: typing.Optional[str] = None,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        result = self.__options.merge_options(baml_options).create_http_request_sync(function_name="ValidateOCRMetadata", args={
            "image": image,"ocr_metadata": ocr_metadata,"body_verses": body_verses,
        }, mode="stream")
        return result
    

b = BamlSyncClient(DoNotUseDirectlyCallManager({}))