# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (2)
# #########################################################################

class BiblicalEra(str, Enum):
    OldTestament = "OldTestament"
    NewTestament = "NewTestament"
    Intertestamental = "Intertestamental"
    ChurchHistory = "ChurchHistory"
    NotApplicable = "NotApplicable"

class EntityCategory(str, Enum):
    Doctrine = "Doctrine"
    Heresy = "Heresy"
    TypeOrSymbol = "TypeOrSymbol"
    BiblicalFigure = "BiblicalFigure"
    HistoricalFigure = "HistoricalFigure"
    CitedAuthority = "CitedAuthority"
    PeopleGroup = "PeopleGroup"
    Location = "Location"
    TimePeriod = "TimePeriod"
    OriginalWord = "OriginalWord"
    ManuscriptOrVersion = "ManuscriptOrVersion"

# #########################################################################
# Generated classes (5)
# #########################################################################

class ExtractedText(BaseModel):
    text: str

class ExtractionResult(BaseModel):
    entities: typing.List["GillEntity"]
    cross_references: typing.List[str]

class GillEntity(BaseModel):
    name: str
    category: EntityCategory
    biblical_era: BiblicalEra
    role: typing.Optional[str] = None
    normalized_name: typing.Optional[str] = None
    description: typing.Optional[str] = None

class Metadata(BaseModel):
    book_name: typing.Optional[str] = None
    chapter: typing.Optional[int] = None
    verse: typing.Optional[str] = None
    page_number: typing.Optional[int] = None

class VerseChunk(BaseModel):
    verse_ref: str
    start_phrase: str
    end_phrase: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
