# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ExtractedText": types.ExtractedText,
    "stream_types.ExtractedText": stream_types.ExtractedText,

    "types.ExtractionResult": types.ExtractionResult,
    "stream_types.ExtractionResult": stream_types.ExtractionResult,

    "types.GillEntity": types.GillEntity,
    "stream_types.GillEntity": stream_types.GillEntity,

    "types.Metadata": types.Metadata,
    "stream_types.Metadata": stream_types.Metadata,

    "types.MetadataCore": types.MetadataCore,
    "stream_types.MetadataCore": stream_types.MetadataCore,

    "types.MetadataVerses": types.MetadataVerses,
    "stream_types.MetadataVerses": stream_types.MetadataVerses,

    "types.VerseChunk": types.VerseChunk,
    "stream_types.VerseChunk": stream_types.VerseChunk,


    "types.BiblicalEra": types.BiblicalEra,

    "types.EntityCategory": types.EntityCategory,

}